name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pick-runner:
    runs-on: ubuntu-latest
    outputs:
      chosen: ${{ steps.pick.outputs.chosen }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - id: pick
        uses: ./.github/actions/pick-runner-action
        with:
          primary-runner: 'self-hosted'
        env:
          GH_TOKEN: ${{ secrets.RUNNER_PICK_TOKEN }}

  quality-check:
    needs: [pick-runner]
    runs-on: ${{ needs.pick-runner.outputs.chosen }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with: { fetch-depth: 0 }
      - name: Run Release Quality Check Action
        uses: ./.github/actions/release-check-action

  build:
    needs: [pick-runner, quality-check]
    if: ${{ needs.quality-check.result == 'success' }} # stop early if QC failed
    runs-on: ${{ needs.pick-runner.outputs.chosen }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with: { fetch-depth: 0 }
      - name: Run Build Action
        uses: ./.github/actions/build-action
        with:
          chosen-runner: ${{ needs.pick-runner.outputs.chosen }}
      - name: Upload build artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: build-artifact
          path: ./dist/rapaglaz-portfolio/browser

  deploy:
    needs: [pick-runner, quality-check, build]
    if: ${{ needs.quality-check.result == 'success' && needs.build.result == 'success' }}
    runs-on: ${{ needs.pick-runner.outputs.chosen }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with: { fetch-depth: 0 }

      - name: Bail out if build failed
        if: ${{ needs.build.result != 'success' }}
        run: |
          echo "Build did not succeed; skipping deploy." >&2
          exit 1

      - name: Download build artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: build-artifact
          path: ./dist/rapaglaz-portfolio/browser

      - name: Deploy (FTP)
        uses: SamKirkland/FTP-Deploy-Action@a51268f67f6605236975928ae28b0f7e9971d50a # v4.3.6
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          server-dir: /
          local-dir: ./dist/rapaglaz-portfolio/browser/
          exclude: |
            package.json
