name: Deploy

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pick-runner:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      chosen: ${{ steps.pick.outputs.chosen }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - id: pick
        uses: ./.github/actions/pick-runner-action
        with:
          primary-runner: 'self-hosted'
        env:
          GH_TOKEN: ${{ secrets.RUNNER_PICK_TOKEN }}

  build:
    needs: [pick-runner]
    runs-on: ${{ needs.pick-runner.outputs.chosen }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with: { fetch-depth: 0 }
      - name: Run Build Action
        uses: ./.github/actions/build-action
        with:
          chosen-runner: ${{ needs.pick-runner.outputs.chosen }}
      - name: Upload build artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: build-artifact
          path: ./dist/rapaglaz-portfolio/browser

  deploy:
    needs: [pick-runner, build]
    runs-on: ${{ needs.pick-runner.outputs.chosen }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with: { fetch-depth: 0 }

      - name: Download build artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: build-artifact
          path: ./dist/rapaglaz-portfolio/browser

      - name: Deploy (FTP)
        uses: SamKirkland/FTP-Deploy-Action@a51268f67f6605236975928ae28b0f7e9971d50a # v4.3.6
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          server-dir: /
          local-dir: ./dist/rapaglaz-portfolio/browser/
